import { supabase } from "@/lib/supabase";
import { mergeKeepingFinished, type PlanRow } from "@/lib/plans";

// Resolve a pending revision on an active week: "apply" makes it the live
// schedule, "discard" keeps the current plan. No AI call — the revision was
// already generated by /api/plan/steer.
export async function POST(request: Request) {
  const { plan_id, decision } = await request.json();

  if (!plan_id || (decision !== "apply" && decision !== "discard")) {
    return Response.json(
      { error: "plan_id and decision (\"apply\" | \"discard\") are required" },
      { status: 400 }
    );
  }

  const { data: planRow, error: planError } = await supabase
    .from("weekly_plans")
    .select("*")
    .eq("id", plan_id)
    .single();

  if (planError || !planRow) {
    return Response.json({ error: "Plan not found" }, { status: 404 });
  }

  const row = planRow as PlanRow;
  const revision = row.plan?.pending_revision;

  if (!revision) {
    return Response.json({ error: "No pending revision on this plan" }, { status: 400 });
  }

  const planWithoutRevision = { ...row.plan };
  delete planWithoutRevision.pending_revision;

  if (decision === "discard") {
    const { data, error } = await supabase
      .from("weekly_plans")
      .update({ plan: planWithoutRevision })
      .eq("id", plan_id)
      .select()
      .single();

    if (error) return Response.json({ error: error.message }, { status: 500 });
    return Response.json({ ...data, mode: "discarded" });
  }

  // Re-merge against the CURRENT schedule rather than trusting the snapshot
  // taken when the revision was proposed — a day may have been finished and
  // logged in between, and completed work must survive the revision.
  const merged = mergeKeepingFinished(row.plan?.schedule || [], revision.schedule);

  const { data, error } = await supabase
    .from("weekly_plans")
    .update({
      plan: {
        ...planWithoutRevision,
        schedule: merged,
        focus_area: revision.focus_area || row.plan?.focus_area,
      },
      priority_recommendation: revision.priority_recommendation || row.priority_recommendation,
    })
    .eq("id", plan_id)
    .select()
    .single();

  if (error) return Response.json({ error: error.message }, { status: 500 });
  return Response.json({ ...data, mode: "applied" });
}
